### ISSUE TITLE
Acesso ao repositóio

### ISSUE THREAD

**Issue by pboueke** [ESEGroup/Brasil#1]

**Comment by pboueke** [comment]
Oi @ffarzat ,

Gostaria de ter acesso ao repositório.

Os outros membros da equipe são: @caiocrr, @lucaslrolim e @vinicius-alves.

Abs,

**Comment by ffarzat** [comment]
Oi @pboueke , vocês já possuem acesso. Conseguir criar essa issue já é uma comprovação.

Todos os demais também já possuem acesso.

Att,
![untitled](https://cloud.githubusercontent.com/assets/1567820/20040645/1834b408-a442-11e6-8191-54f9a67a044f.png)

**Comment by pboueke** [comment]
Oi @ffarzat,

Obrigado pela resposta. O problema é que eu não tenho permissão para fazer nada, sou apenas um membro da equipe. Gostaria, além de gerenciar o desenvolvimento pela seção de 'projetos', criar um banch gh-pages para colocar o mockup do frontend no ar. 

Podemos fazer isso em outro repositório/fork (e se for essa a ideia, não há problema), mas achei que seria interessante centralizar aqui.

Abs,

![denied](https://cloud.githubusercontent.com/assets/5193692/20040709/4b4089e8-a443-11e6-90be-5f5555ede9dc.png)

**Comment by ffarzat** [comment]
Oi @pboueke , de fato o grupo estava com acesso de leitura. Teste de novo por favor. Se funcionar, pode fechar a issue.

Att,

**Comment by pboueke** [comment]
Obrigado!
