### ISSUE TITLE
Mockups do sistema

### ISSUE THREAD

**Issue by pboueke** [ESEGroup/Brasil#10]
Criação de mockups para facilitar o desenvolvimento das telas por parte da equipe e também permitir aos stakeholders uma visão geral sobre como se espera desenvolver o sistema.

**Comment by pboueke** [comment]
@lucaslrolim  discuta aqui o que fizer. Use algo colaborativo/editável por favor.

**Comment by lucaslrolim** [comment]
Para a criação dos Mockups foi usada a ferramenta Balsamiq Mockups. Essa é uma das ferramentas com maior utilização do mercado e possui versão de testes gratuita.

O link com todos os arquivos editáveis gerados é

[Arquivos Mockup](https://drive.google.com/open?id=0B3H39qo1SMWNQ0RjSW93MHBrUWs)

E o link do projeto final é

[Mockups Agendae - Final](https://drive.google.com/file/d/0B3H39qo1SMWNX0ZyWjE0bno1dWc/view?usp=sharing)
