### ISSUE TITLE
Backend integration

### ISSUE THREAD

**Issue by pboueke** [ESEGroup/Brasil#3]
Temos que decidir como vai ser a arquitetura do projeto.

@lucaslrolim @caiocrr @vinicius-alves

**Comment by pboueke** [comment]
Estou tentando tirar tempo para estuar uma arquitetura servless utilizando as "function" da Azure. Me parece interessante, mas ainda não cheguei a testar

**Comment by vinicius-alves** [comment]
Concordo em usar o Azure, não conheço muito sobre a arquitetura servless. Poderíamos utilizar Nodejs e fazer um MVC do lado do servidor e do lado do cliente.

**Comment by pboueke** [comment]
Do documento de diretrizes:
"
- Há uma restrição arquitetural que deve ser obedecida. É obrigatório o uso do padrão
  de projeto Model-View-Controller (MVC), em sua variação prática, organizado em
  camadas, conforme apresentado na aula de arquitetura de software
- Sugestão: utilizar o padrão Data-Access-Object(DAO) para comunicação da
  aplicação com o Banco de Dados
  "
  Ok, então podemos fazer da forma sugerida, @vinicius-alves .

**Comment by pboueke** [comment]
Ok, as discussões estão seguindo em outras threads, vou fechar essa aqui.
