### ISSUE TITLE
Diagrama de Classes (Model - Backend)

### ISSUE THREAD

**Issue by vinicius-alves** [ESEGroup/Brasil#4]
Boa tarde a todos.
Abaixo um modelo inicial do diagrama de classes para o backend
Se possível, apontem correções ou modificações necessárias

[Diagrama](https://docs.google.com/a/poli.ufrj.br/document/d/1nFCopAE3IwNPjU3knOmjjXjxKJPFHNdkVugvddB5Dp8/edit?usp=sharing)

**Comment by pboueke** [comment]
Acho interessante adicionar um campo de descrição no obj do recurso para auxiliar a busca.

**Comment by vinicius-alves** [comment]
> Acho interessante adicionar um campo de descrição no obj do recurso para auxiliar a busca.

Adicionado!
