### ISSUE TITLE
Diagramas de Sequência

### ISSUE THREAD

**Issue by pboueke** [ESEGroup/Brasil#6]

**Comment by vinicius-alves** [comment]
Boa tarde, @ffarzat @hneri 

Tudo bem? Estamos fazendo os diagramas de sequência, porém não sabemos se está correto. Poderia nos dar sua opinião? 

![diagram_seq](https://cloud.githubusercontent.com/assets/19786713/20224026/85ee9268-a823-11e6-9672-e8ba576e293e.png)

E o diagrama de classes referente especificamente a este caso é:

![diagram_class](https://cloud.githubusercontent.com/assets/19786713/20224047/a8021e7e-a823-11e6-9027-1c7230c4e5b4.png)
